# Generated by Django 3.2.7 on 2021-10-24 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20211023_1759'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
