# Generated by Django 3.2.7 on 2021-10-24 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
    ]
