# Generated by Django 3.2.7 on 2021-10-24 03:05

from django.db import migrations, models
import website.storage


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.FileField(storage=website.storage.OverwriteStorage(), upload_to='image/'),
        ),
    ]
