# Generated by Django 3.2.8 on 2021-10-24 05:26

from django.db import migrations, models
import website.storage


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_image_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('solutions', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.FileField(storage=website.storage.OverwriteStorage(), upload_to='images/med.png'),
        ),
    ]
