# Generated by Django 3.2.8 on 2021-10-24 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_image_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Object',
            new_name='Items',
        ),
    ]
